version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.9.0
    steps:
      - checkout
      - run:
          name: Install Python dependencies 
          command: |
            echo 'being setup env variables'
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
            echo 'all package installed'
            echo 'Now install ML packaged lib'
            pip install --user .
      - run:
          name: Run Unit test for ML model
          command: |
            echo 'run test'
            pytest ml/tests --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
            echo 'test success'
workflows:
  build_test:
    jobs:
      - run_tests

