version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.9.0
    steps:
      - checkout
      - run:
          name: Install Python dependencies 
          command: |
            echo 'being setup env variables'
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
            pip install --user .
      - run:
          name: Run Unit test for ML Model
          command: |
            pytest ml/tests 
      - run:
          name: Run Unit test for Flask Web App
          command: |
            pytest web-app/tests
workflows:
  build_test:
    jobs:
      - run_tests

