version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.9.0
    steps:
      - checkout
      - run:
          name: Install Python dependencies 
          command: |
            echo 'being setup env variables'
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
            echo 'all package installed'

workflows:
  build_test:
    jobs:
      - run_tests

